apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: rtmp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtmp-server
  template:
    metadata:
      labels:
        app: rtmp-server
    spec:
      containers:
        - name: rtmp-server
          image: lighterror/react-rtmp-stream-server #this is dockerhub image (not local)
          ports:
            - name: front-shell
              containerPort: 8000
            - name: rtmp-port
              containerPort: 1935
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: rtmp-server
  type: LoadBalancer
  ports:
    - name: front-shell
      port: 8000
      targetPort: 8000
    - name: rtmp-port
      port: 1935
      targetPort: 1935
